AllCops:
  TargetRubyVersion: 2.4

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Lambda:
  EnforcedStyle: literal

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'db/**/*.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/**/*.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'

Lint/AssignmentInCondition:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces

Style/Documentation:
  Exclude:
    - 'db/**/*.rb'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 40
