default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER", "tourneybikepolo-be") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>

development:
  <<: *default
  database: tourneybikepolo-be_development

test:
  <<: *default
  database: tourneybikepolo-be_test

production:
  <<: *default
  database: tourneybikepolo-be_production
  username: tourneybikepolo-be
  password: <%= ENV['TOURNEYBIKEPOLO-BE_DATABASE_PASSWORD'] %>
