default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch('PGDATABASE', 'tourneybikepolo_development') %>
  username: tourneybikepolo
  password:
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '5432') %>
  schema_search_path: myapp,sharedapp,public
  min_messages: notice

test:
  <<: *default
  database: tourneybikepolo_test
  username: tourneybikepolo
  password:
  host: <%= ENV.fetch('PGHOST', '127.0.0.1') %>
  port: <%= ENV.fetch('PGPORT', '5432') %>

production:
  <<: *default
  database: tourneybikepolo_production
  username: tourneybikepolo
  password: <%= ENV['TOURNEYBIKEPOLO-BE_DATABASE_PASSWORD'] %>
