default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.development.dig(:db, :host) %>
  port: <%= Rails.application.credentials.development.dig(:db, :port) %>
  username: <%= Rails.application.credentials.development.dig(:db, :username) %>
  password: <%= Rails.application.credentials.development.dig(:db, :password) %>

development:
  <<: *default
  database: tourneybikepolo-be_development

test:
  <<: *default
  database: tourneybikepolo-be_test

production:
  <<: *default
  database: tourneybikepolo-be_production
  username: tourneybikepolo-be
  password: <%= ENV['TOURNEYBIKEPOLO-BE_DATABASE_PASSWORD'] %>
